openapi: 3.0.1
info:
  title: Ryanair Routes API
  version: 1.0.0
paths:
  /views/locate/3/routes:
    get:
      summary: Get available Ryanair routes
      responses:
        '200':
          description: List of routes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Route'
components:
  schemas:
    Route:
      type: object
      properties:
        airportFrom:
          type: string
        airportTo:
          type: string
        connectingAirport:
          type: string
          nullable: true
        newRoute:
          type: boolean
        seasonalRoute:
          type: boolean
        operator:
          type: string
        group:
          type: string
