openapi: 3.0.1
info:
  title: Ryanair Interconnections API
  version: 1.0.0
paths:
  /v1/interconnections:
    get:
      operationId: getInterconnections
      tags:
        - interconnections
      summary: Get direct and 1-stop interconnections
      parameters:
        - name: departure
          in: query
          required: true
          schema:
            type: string
        - name: arrival
          in: query
          required: true
          schema:
            type: string
        - name: departureDateTime
          in: query
          required: true
          schema:
            type: string
            format: local-date-time
        - name: arrivalDateTime
          in: query
          required: true
          schema:
            type: string
            format: local-date-time
      responses:
        '200':
          description: List of valid flight connections
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connection'
        '400':
          description: Bad request, e.g. missing parameters or invalid date format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error, e.g. database connection issues
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Connection:
      type: object
      properties:
        stops:
          type: integer
        legs:
          type: array
          items:
            $ref: '#/components/schemas/Leg'
    Leg:
      type: object
      properties:
        departureAirport:
          type: string
        arrivalAirport:
          type: string
        departureDateTime:
          type: string
          format: local-date-time
        arrivalDateTime:
          type: string
          format: local-date-time
    Error:
      type: object
      properties:
        code:
          type: integer
          example: 4001
        message:
          type: string
          example: "Invalid input parameters"
        details:
          type: string
          example: "The departure date must be in the future and in ISO 8601 format"

