name: Java CI with Coverage

# Build on pushes and PRs against master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Grant the token enough rights to post PR comments
permissions:
  contents: read          # allow checkout
  pull-requests: write    # allow gh pr comment

jobs:
  # BUILD & TEST
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21 + cache Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build, test and generate reports
        run: |
          mvn -B clean verify \
                 spotbugs:spotbugs \
                 jacoco:report

      # Upload artifacts for the coverage and bug reports
      - uses: actions/upload-artifact@v4
        with:
          name: jacoco-html
          path: target/site/jacoco

      - uses: actions/upload-artifact@v4
        with:
          name: jacoco-badges
          path: badges

  # Comment coverage in the Pull Request after generating badges
  coverage:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Download JaCoCo report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-html
          path: report

      - name: Generate JaCoCo badges / summary
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: report/jacoco.csv
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true

      - name: Format JaCoCo summary for PR
        id: coverage
        run: |
          summary=$(cat badges/coverage-summary.json)
          cov=$(jq -r '.coverage' <<<"$summary")%
          br=$(jq -r '.branches' <<<"$summary")%
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "## ✅ JaCoCo Coverage Report" >> $GITHUB_OUTPUT
          echo "* **Line Coverage:** $cov" >> $GITHUB_OUTPUT
          echo "* **Branch Coverage:** $br" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post or update PR comment with coverage
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.coverage.outputs.body }}